name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            cd /
            rm -rf /var/www/data-sheet-app/
            rm -rf /home/cloned-repo-data-sheet-app/
            cd /var/www
            mkdir data-sheet-app
            cd /home
            mkdir cloned-repo-data-sheet-app
            cd cloned-repo-data-sheet-app
            git clone https://github.com/Andrii-Yukhymenko/data-sheet-app.git
            cd data-sheet-app/
            npm install
            npm run build
            cp -r build/* /var/www/data-sheet-app
